"""Initial migration

Revision ID: 0c0b561a6bcb
Revises: 
Create Date: 2025-01-06 15:03:25.147722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c0b561a6bcb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('extraction_order',
    sa.Column('Day', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('delivery_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Customer', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Customer address', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('hubs', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ShipTo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('truck', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Driver', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('assets', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Product', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ShipTo address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('shift_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delivery_starttime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('delivery_endtime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.create_table('loading_order_report',
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('terminal_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('supplier_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Product', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('gross_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('net_amount', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('shift_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('bol', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('driver', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('truck', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('compartment', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('fp_compartment_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('order_group_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('started_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.create_table('moffitt',
    sa.Column('Drivers', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('OTP', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Hubs', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('Line Of Service', sa.VARCHAR(length=100), autoincrement=False, nullable=True)
    )
    op.create_table('moffitt_assets_report',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Ownership type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ship_to_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ship_to_erp', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ship_to_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('license_plate_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('erp_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Asset Type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Hub', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Tank Size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('LoS', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    op.create_table('delivery_order_report',
    sa.Column('Day', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('delivery_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('shift_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Customer', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Customer address', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ShipTo', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('ShipTo address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('Driver', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('Product', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assets', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hubs', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('truck', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('delivery_asset', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('delivery_starttime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('delivery_endtime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('item_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    op.create_table('training_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('user_query', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('generated_sql', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('query_results', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='training_data_pkey')
    )
    op.create_table('cleaned_moffitt_customers_list',
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('erp_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ship_to', sa.VARCHAR(length=32767), autoincrement=False, nullable=True)
    )
    op.create_table('customer_data_with_cities',
    sa.Column('customer name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ship_to_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ship_to_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ship_to_erp_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_delivery_date_cst', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('customer_erp_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('customer_address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('asset_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delivery_orders_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True)
    )
    op.create_table('cleaned_customer_location',
    sa.Column('customer name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ship_to_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ship_to_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ship_to_erp_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_delivery_date_cst', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('customer_erp_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('customer_address', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('asset_count', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('delivery_orders_count', sa.VARCHAR(length=100), autoincrement=False, nullable=True)
    )
    op.create_table('transfer_order_report',
    sa.Column('transferred_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('shift', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('order_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('order_worker', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('from_shift', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('to_shift', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('from_driver', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('from_asset', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('from_compartment', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('from_compartment_fp_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('to_driver', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('to_asset', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('to_compartment', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('to_compartment_fp_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_order_report')
    op.drop_table('cleaned_customer_location')
    op.drop_table('customer_data_with_cities')
    op.drop_table('cleaned_moffitt_customers_list')
    op.drop_table('training_data')
    op.drop_table('delivery_order_report')
    op.drop_table('moffitt_assets_report')
    op.drop_table('moffitt')
    op.drop_table('loading_order_report')
    op.drop_table('extraction_order')
    op.drop_table('users')

    # ### end Alembic commands ###
    # ### end Alembic commands ###